pub mod author;
pub mod client;
pub mod client_blocking;
pub mod date;
pub mod error;
pub mod funding;
pub mod membership;
pub mod organization;
pub mod peer_review;
pub mod publication_date;
pub mod qualification;
pub mod role;
pub mod search_builder;
pub mod utils;
pub mod work;

// Re-export public structs for convenience
pub use author::Author;
pub use client::Client;
pub use client_blocking::ClientBlocking;
pub use date::Date;
pub use error::{OrcidError, Result};
pub use funding::Funding;
pub use membership::Membership;
pub use organization::Organization;
pub use peer_review::PeerReview;
pub use publication_date::PublicationDate;
pub use qualification::Qualification;
pub use role::Role;
pub use search_builder::SearchBuilder;
pub use work::Work;
